[refactor][kubectl-plugin] require cluster in `create workergroup`
command in the Cobra way.

## Before

```console
$ kubectl ray --context gke_kubeflow-platform_europe-west4-b_ml-compute-1 create workergroup -n hyperkube other-group
Error: error getting Ray cluster: resource name may not be empty
```

## After

```console
$ kubectl ray create workergroup other-group
Error: required flag(s) "ray-cluster" not set
```

Signed-off-by: David Xia <david@davidxia.com>