[refactor][kubectl-plugin] require one posarg in `session` and `log`
command with a custom Cobra `Command.Args` function instead of writing our own
logic in `Complete()`.

## Before

```console
$ kubectl ray session

Error: session (RAYCLUSTER | TYPE/NAME)
See 'ray session -h' for help and examples

$ kubectl ray logs

Error: log (RAYCLUSTER | TYPE/NAME) [--out-dir DIR_PATH] [--node-type all|head|worker]
See 'ray log -h' for help and examples
```

## After

```console
$ kubectl ray session

Error: accepts 1 arg, received 0
session (RAYCLUSTER | TYPE/NAME)
See 'ray session -h' for help and examples

$ kubectl ray logs

Error: accepts 1 arg, received 0
log (RAYCLUSTER | TYPE/NAME) [--out-dir DIR_PATH] [--node-type all|head|worker]
See 'ray log -h' for help and examples
```

Signed-off-by: David Xia <david@davidxia.com>