[fix][kubectl-plugin] use explicit context for session cmd
when there's no implicit current context set.

Right now if there's no current context set but an explicit one is with
`kubectl ray --context CONTEXT session ...`, the command gets stuck in a retry
loop because it cannot find the RayCluster.

This change puts the explicitly specified context into the command `kubectl
--context CONTEXT port-forward ...` so that the command can find the
RayCluster.

We also add a `-v/--verbose` flag that shows the `kubectl port-forward` command
for debugging.

## Before

```console
$ kubectl config unset current-context
Property "current-context" unset.

$ kubectl ray --context CONTEXT -n NAMESPACE session CLUSTER_NAME
Forwarding ports to service CLUSTER_NAME-head-svc
Ray Dashboard: http://localhost:8265
Ray Interactive Client: http://localhost:10001

failed to port-forward: exit status 1, try to reconnect after 100 miliseconds...
failed to port-forward: exit status 1, try to reconnect after 100 miliseconds...
...
```

## After

```console
$ kubectl config unset current-context
Property "current-context" unset.

$ kubectl ray -n NAMESPACE session CLUSTER_NAME
Error: no context is currently set, use "--context" or "kubectl config use-context <context>" to select a new one

$ kubectl ray --context CONTEXT -n NAMESPACE session CLUSTER_NAME
Forwarding ports to service CLUSTER_NAME-head-svc
Ray Dashboard: http://localhost:8265
Ray Interactive Client: http://localhost:10001

$ kubectl ray --context CONTEXT -n NAMESPACE session CLUSTER_NAME -v
Forwarding ports to service CLUSTER_NAME-head-svc
Ray Dashboard: http://localhost:8265
Ray Interactive Client: http://localhost:10001

Running: kubectl --context CONTEXT port-forward -n NAMESPACE service/CLUSTER_NAME-head-svc 8265:8265 10001:10001
```

Signed-off-by: David Xia <david@davidxia.com>